-- Create contacts table
create table public.contacts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  subject text not null,
  message text not null,
  phone text,
  company text,
  project_type text,
  budget_range text,
  timeline text,
  newsletter_signup boolean default false,
  read boolean default false
);

-- Enable Row Level Security (RLS)
alter table public.contacts enable row level security;

-- Policies
create policy "Enable read access for all users" on public.contacts for select using (true);
create policy "Enable insert access for all users" on public.contacts for insert with check (true);
create policy "Enable update access for all users" on public.contacts for update using (true);
create policy "Enable delete access for all users" on public.contacts for delete using (true);
