-- Create projects table
create table public.projects (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  slug text not null unique,
  description text,
  excerpt text,
  client text,
  services text[], -- Array of strings
  industry text,
  tags text[],     -- Array of strings
  challenge_summary text,
  challenge_description text,
  solution_summary text,
  solution_description text,
  client_feedback text,
  client_name text,
  client_role text,
  client_company text,
  client_company_url text,
  image_url text,
  github_url text,
  live_url text,
  category text,
  featured boolean default false
);

-- Create blog_posts table
create table public.blog_posts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  slug text not null unique,
  content text,
  excerpt text,
  author text,
  category text,
  tags text[],     -- Array of strings
  featured_image text,
  published boolean default false
);

-- Enable Row Level Security (RLS) - Optional but recommended
alter table public.projects enable row level security;
alter table public.blog_posts enable row level security;

-- Create policies to allow public read access (since admin is public/no-login)
-- WARNING: These policies allow ANYONE to read/write if you don't restrict them further.
-- Since you requested "no login needed for the admin", we will allow public access for now.
-- Ideally, you should restrict write access to authenticated users or specific IP addresses.

-- Policy for Projects
create policy "Enable read access for all users" on public.projects for select using (true);
create policy "Enable insert access for all users" on public.projects for insert with check (true);
create policy "Enable update access for all users" on public.projects for update using (true);
create policy "Enable delete access for all users" on public.projects for delete using (true);

-- Policy for Blog Posts
create policy "Enable read access for all users" on public.blog_posts for select using (true);
create policy "Enable insert access for all users" on public.blog_posts for insert with check (true);
create policy "Enable update access for all users" on public.blog_posts for update using (true);
create policy "Enable delete access for all users" on public.blog_posts for delete using (true);
